#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
  path: /
  controller: App\Controller\WelcomeController::welcome

admin:
  path: /admin/test
  controller: App\Controller\AdminController::test

products:
  path: /products
  controller: App\Controller\ProductController::userIndex

events:
  path: /events
  controller: App\Controller\EventController::userIndex