#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
  path: /
  controller: App\Controller\WelcomeController::welcome

admin:
  path: /admin/test
  controller: App\Controller\AdminController::test